Atom molecule
arrogant-ant/parkspot pull request #150
Opened 2022-06-28 18:18 UTC by alias01

Please review

2022-07-12 02:05 UTC, arrogant-ant commented
please remove dist dir changes and then push.

2022-07-13 06:26 UTC, alias01 commented on src/components/atoms/AtomButtons.vue
> +        return value.match(/(is-danger)/);
is-warning is bulma css that uses the primary color yellow that our website

2022-07-13 06:28 UTC, alias01 commented on src/components/atoms/AtomInputs.vue
> +  name: "AtomInputs",
it is used because old atom also used the same name to differentiate added 's' to every new atom component

2022-07-13 06:28 UTC, alias01 commented on src/components/atoms/AtomButtons.vue
> +  name: "AtomButtons",
it is used because old atom also used the same name to differentiate added 's' to every new atom component

2022-07-19 04:53 UTC, arrogant-ant requested changes

2022-07-19 05:20 UTC, alias01 commented on src/components/atoms/AtomUploads.vue
> +  name: "AtomUploads",
it is used because old atom also used the same name to differentiate added 's' to every new atom component

2022-07-19 05:20 UTC, alias01 commented on src/components/atoms/AtomRadioButtons.vue
> +  name: "AtomRadioButtons",
it is used because old atom also used the same name to differentiate added 's' to every new atom component

2022-07-19 05:24 UTC, alias01 commented on src/components/atoms/AtomSelectInput.vue
> +    data: {
will push the changes in next Change.

2022-09-02 17:32 UTC, closed without merging