Search portal
arrogant-ant/parkspot pull request #161
Opened 2022-08-05 20:11 UTC by alias01

please review

2022-08-14 13:18 UTC, arrogant-ant commented
@alias01 why images are moved inside backup dir?

2022-08-14 13:20 UTC, arrogant-ant requested changes

2022-08-14 13:20 UTC, arrogant-ant commented on src/components/molecules/MoleculeSRPCard.vue
> +      <img :alt="'parking spot image'" :src="spot.IconURL" />
Start alt text with capital letter.
`Parking`

2022-08-29 16:02 UTC, arrogant-ant requested changes

2022-08-29 16:02 UTC, arrogant-ant commented on src/views/PageVOPortal.vue
> +        console.error({ error });
if intentional logging then please add some identifier.

2022-09-01 17:03 UTC, alias01 commented on src/components/extras/SearchInput.vue
> +      this.updateSelectedCity(newValue.context[0].text); // update selected city
ve

2022-09-01 17:03 UTC, alias01 commented on src/assets/styles/variables.css
> +    --lh-default:1;
stylelint introduce in later PR...so not needed now

2022-09-01 17:09 UTC, alias01 commented on src/components/atoms/AtomSelectInput.vue
> +  // methods: {
next Pr

2022-09-01 17:09 UTC, alias01 commented on src/components/atoms/AtomSelectInput.vue
> +    list: {
next PR

2022-09-01 17:09 UTC, alias01 commented on src/components/atoms/AtomUpload.vue
> +  emits: ["uploadFiles"],
done

2022-09-01 17:10 UTC, alias01 commented on src/components/extras/MapContainer.vue
> +  mounted() {
next PR

2022-09-01 17:15 UTC, alias01 commented on src/components/organisms/OrganismPreferenceForm.vue
> +              this.$emit("formValidate", el);
done

2022-09-01 17:17 UTC, alias01 commented on src/components/templates/TemplateNearBy.vue
> +      <!-- <div>
done

2022-09-01 17:17 UTC, alias01 commented on src/components/templates/TemplateNearBy.vue
> +// import SearchInput from "../extras/SearchInput.vue";
done

2022-09-01 17:18 UTC, alias01 commented on src/components/templates/TemplateNearBy.vue
> +    // SearchInput,
done

2022-09-01 17:18 UTC, alias01 commented on src/components/templates/TemplateNearBy.vue
> +  .custom-title {
done

2022-09-01 17:18 UTC, alias01 commented on src/components/templates/TemplateOurProducts.vue
> +      this.$emit("arrowBtn");
task created for this in rock

2022-09-01 17:18 UTC, alias01 commented on src/components/templates/TemplateSOPortal.vue
> +  emits: ["finalSubmit"],
task created

2022-09-01 17:21 UTC, alias01 commented on src/components/templates/TemplateSrp.vue
> +      <Pagination :totals="totals" @changed="onPageChange"></Pagination>
done

2022-09-01 17:21 UTC, alias01 commented on src/components/templates/TemplateThankYou.vue
> +  emits: ["homeBtn"],
task created

2022-09-01 17:24 UTC, alias01 commented on src/components/templates/TemplateVOPortal.vue
> +          :type="btnStack[0] ? 'is-success' : 'is-warning'"
will think about it

2022-09-01 17:24 UTC, alias01 commented on src/components/templates/TemplateVOPortal.vue
> +  emits: ["finalSubmit"],
task created for this already

2022-09-01 17:34 UTC, alias01 commented on src/inlcudes/ConvertImageToByte.js
> +function getConvertedImage(data) {
done

2022-09-01 17:35 UTC, alias01 commented on src/main.js
> +// import VueResource from "vue-resource";
done

2022-09-01 17:35 UTC, alias01 commented on src/main.js
> +// Vue.use(VueResource);
done

2022-09-01 17:36 UTC, alias01 commented on src/services/api.js
> +      // Flavour: flavour,
done

2022-09-01 18:19 UTC, arrogant-ant approved these changes

2022-09-02 17:32 UTC, closed without merging