Metainfo
arrogant-ant/parkspot pull request #205
Opened 2022-11-23 17:51 UTC by alias01

2022-11-23 18:48 UTC, arrogant-ant approved these changes

2022-11-23 18:49 UTC, arrogant-ant requested changes

2022-11-23 18:49 UTC, arrogant-ant commented on src/constant/constant.js
> +    SOPORTAL: 'Register Parking Spot',
SO_PORTAL

2022-11-24 10:36 UTC, alias01 commented on src/constant/constant.js
> +    VOPORTAL: 'Get Parking Spot',
done

2022-11-24 10:36 UTC, alias01 commented on src/constant/constant.js
> +    SOPORTAL: 'Register Parking Spot',
done

2022-11-24 18:03 UTC, arrogant-ant approved these changes

2022-11-24 18:03 UTC, merged