Profile form addition
arrogant-ant/parkspot pull request #288
Opened 2023-06-25 07:58 UTC by alias01

2023-07-05 05:10 UTC, arrogant-ant requested changes

2023-07-05 05:10 UTC, arrogant-ant commented on src/store/user/index.js
>              // Handle Errors here.
unnecessary comment

2023-07-08 03:48 UTC, alias01 commented on src/components/atoms/AtomCheckbox.vue
> +        checkboxGroup(newVal) {
done

2023-07-08 03:56 UTC, alias01 commented on src/components/organisms/OrganismParkingFacility.vue
> +            <div class="parking-facility-form-SO" v-if="userProfile.Type === 1">
done

2023-07-08 03:57 UTC, alias01 commented on src/components/organisms/OrganismUserGeneralInfo.vue
> +        <LoaderModal :isLoading="isLoading"></LoaderModal>
this could be different discussion not related to this ticket..as it will change the overall logic in the app

2023-07-08 04:05 UTC, alias01 commented on src/components/organisms/OrganismUserGeneralInfo.vue
> +                        this.localType = 0;
done

2023-07-08 12:10 UTC, merged