recent search added
arrogant-ant/parkspot pull request #289
Opened 2023-06-25 10:25 UTC by alias01

2023-07-05 05:12 UTC, arrogant-ant requested changes

2023-07-05 05:12 UTC, arrogant-ant commented on src/components/extras/SearchInput.vue
> +                            <!-- fromLS should be renamed -->
planning to rename in this PR.

2023-07-05 05:12 UTC, arrogant-ant commented on src/components/extras/SearchInput.vue
> +        async displayRecentSearches() {
is this method needed

2023-07-08 03:33 UTC, alias01 commented on src/components/extras/SearchInput.vue
> +        async displayRecentSearches() {
yes added again

2023-07-08 03:33 UTC, merged