Booking portal/payment link
arrogant-ant/parkspot pull request #305
Opened 2023-07-16 11:50 UTC by alias01

2023-07-19 16:07 UTC, arrogant-ant requested changes

2023-07-19 16:07 UTC, arrogant-ant commented on src/store/bookingPortal/index.js
> +    'set-payment-details'(state, paymentDetails) {
add new line before every mutation and functions.

2023-07-19 16:07 UTC, arrogant-ant commented on src/store/bookingPortal/index.js
> +    async getPaymentLink({ dispatch, commit }, reqBody) {
add new  line before methods

2023-07-19 16:07 UTC, arrogant-ant commented on src/store/bookingPortal/index.js
> +        if (res) {
if there is an error maya will still send res with DisplayMsg but without any paymentDetails
So this condition will still evaluate true
Else condition will never be evaluated

2023-07-20 12:54 UTC, alias01 commented on src/store/bookingPortal/index.js
> +    async getPaymentLink({ dispatch, commit }, reqBody) {
done

2023-07-21 04:55 UTC, arrogant-ant approved these changes

2023-07-21 04:55 UTC, merged