Backend for agent Book
arrogant-ant/parkspot pull request #441
Opened 2024-10-27 16:38 UTC by VineetMittal007

Integrating Apis for GET and POST, 
adding enum: Parkingrequeststatus
adding route : parkspot.in/internal/register-request

2024-10-28 17:57 UTC, arrogant-ant requested changes

2024-10-28 17:57 UTC, arrogant-ant commented on src/store/agentBook/index.js
> +            const data= await mayaClient.get(`/internal/parking-requests?mobile=${state.formData.Mobile}`);
rename data to something meaningful

2024-10-28 17:57 UTC, arrogant-ant commented on src/store/agentBook/index.js
> +            let assignedRequest = false;
move checking already assigned agent to a different function

2024-10-28 18:03 UTC, VineetMittal007 commented on src/router/routes.js
> +        name: 'agent-booking-portal',
should i rename it as AGENT_BOOK or AGENT_REQUEST or REGISTER_REQUEST ?

2024-10-29 12:10 UTC, arrogant-ant approved these changes

2024-10-29 12:12 UTC, merged