Page vo portal/search component
arrogant-ant/parkspot pull request #478
Opened 2024-12-05 09:10 UTC by Saksham2k3s

![SearchComponent](https://github.com/user-attachments/assets/7e379e96-5039-4dde-ac95-2d39dafd24b5)

2024-12-06 14:11 UTC, arrogant-ant requested changes

2024-12-06 14:11 UTC, arrogant-ant commented on src/components/atoms/AtomButton.vue
> +        :class="{'btn-border-radius': withSearch}"
Please keep the bindings sorted

2024-12-06 14:11 UTC, arrogant-ant commented on src/components/vo-portal/SearchComponent.vue
> +            items: TOP_SEARCH_PLACES
Please add a TODO to fetch this from firebase

2024-12-06 14:34 UTC, Saksham2k3s commented
@arrogant-ant Apply requested changes

2024-12-14 14:40 UTC, arrogant-ant approved these changes

2024-12-14 16:51 UTC, merged