Page vo portal/testimonial component
arrogant-ant/parkspot pull request #479
Opened 2024-12-05 09:52 UTC by Saksham2k3s

![testimonialCard](https://github.com/user-attachments/assets/fe1ce577-ad7c-4b0e-b157-c13169b38e8e)

2024-12-06 14:16 UTC, arrogant-ant requested changes

2024-12-06 14:16 UTC, arrogant-ant commented on src/components/global/TestimonialSection.vue
> +                <!-- Additional required wrapper -->
this comment is not clear

2024-12-06 14:16 UTC, arrogant-ant commented on src/components/global/TestimonialSection.vue
> +            background-image: url("data:image/svg+xml,%0A%3Csvg width='9px' height='16px' viewBox='0 0 9 16' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink
please add some comment, if this was copied then the URL of the original

2024-12-07 08:08 UTC, Saksham2k3s commented
@arrogant-ant Apply requested Changes

2024-12-07 08:47 UTC, merged