Retrieve Map Access Token from Firebase
arrogant-ant/parkspot pull request #502
Opened 2024-12-28 15:56 UTC by Saksham2k3s

This PR introduces functionality to securely retrieve the Mapbox access token from Firebase.

2024-12-30 18:59 UTC, arrogant-ant requested changes

2024-12-30 18:59 UTC, arrogant-ant commented on src/components/extras/MapContainer.vue
> +                mapboxgl.accessToken = this.accessToken;
consider breaking this block into smaller methods.

2024-12-30 18:59 UTC, arrogant-ant commented on src/components/extras/MapContainer.vue
> +            const keys = await getValueFromFirebase(
consider storing this in cookies (with 15 days expiry)

2024-12-30 18:59 UTC, arrogant-ant commented on src/components/extras/MapContainer.vue
> -            accessToken: process.env.VUE_APP_MAP_ACCESS_TOKEN,
since `VUE_APP_MAP_ACCESS_TOKEN` is not in use. Please remove the variable too.

2025-01-02 14:14 UTC, arrogant-ant requested changes

2025-01-02 14:14 UTC, arrogant-ant commented on src/components/extras/MapContainer.vue
> +            if (this.accessToken) {
instead of keep the entire code in if block, better to do a negation
```
 if (!this.accessToke){
    return
}
.
.
.
```

2025-01-02 14:14 UTC, arrogant-ant commented on src/components/extras/MapContainer.vue
> +          </button>
extract this to a method, `getPsPopup(spot)`

2025-01-03 06:25 UTC, arrogant-ant approved these changes

2025-01-03 06:25 UTC, arrogant-ant commented on src/components/extras/MapContainer.vue
> +                const encodedSpotId = encodeURIComponent(spot.ID);
is encodedSpotId is used only inside `getPsPopup`, it can be declared in the method itself.

2025-01-03 12:56 UTC, Saksham2k3s commented on src/components/extras/MapContainer.vue
> +                const encodedSpotId = encodeURIComponent(spot.ID);
Yes, we are using encodedSpotId inside geetPsPopup method

2025-01-03 13:05 UTC, arrogant-ant requested changes

2025-01-03 13:05 UTC, arrogant-ant commented on src/components/extras/MapContainer.vue
> +                const encodedSpotId = encodeURIComponent(spot.ID);
Dont declare this variable here. Move it inside `getPsPopup`

2025-01-03 13:06 UTC, arrogant-ant approved these changes

2025-01-03 13:55 UTC, Saksham2k3s commented on src/components/extras/MapContainer.vue
> +                const encodedSpotId = encodeURIComponent(spot.ID);
@arrogant-ant sir I have moved encodedSpotId inside the getPsPopup method.

2025-01-03 16:20 UTC, merged